{% set version = "1.0.2" %}

package:
  name: importlib_resources
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/importlib_resources/importlib_resources-{{ version }}.tar.gz
  sha256: d3279fd0f6f847cced9f7acc19bd3e5df54d34f93a2e7bb5f238f81545787078

build:
  number: 1000
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - pathlib2  # [py27]
    - typing  # [py<35]
  run:
    - python
    - pathlib2  # [py27]
    - typing  # [py<35]

test:
  imports:
    - importlib_resources

about:
  home: http://importlib-resources.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE
  summary: "Backport of Python 3.7's standard library `importlib.resources`."

extra:
  recipe-maintainers:
    - ocefpaf
