{% set version = "1.0" %}

package:
  name: importlib_resources
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/importlib_resources/importlib_resources-{{ version }}.tar.gz
  sha256: bd15a50b5d14749c0f9fa56986fe45988a5e3a8604ca09ca67b1a3ccc499d028

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - pathlib2  # [py27]
    - typing  # [py<35]
  run:
    - python
    - pathlib2  # [py27]
    - typing  # [py<35]

test:
  imports:
    - importlib_resources

about:
  home: http://importlib-resources.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE
  summary: "Backport of Python 3.7's standard library `importlib.resources`."

extra:
  recipe-maintainers:
    - ocefpaf
