{% set version = "5.2.0" %}

package:
  name: importlib_resources
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/importlib_resources/importlib_resources-{{ version }}.tar.gz
  sha256: 22a2c42d8c6a1d30aa8a0e1f57293725bfd5c013d562585e46aff469e0ff78b3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - wheel
    - setuptools >=42
    # setuptools_scm[toml] from upstream source
    - setuptools_scm >=3.4.1
    - toml
  run:
    - python >=3.6
    - zipp >=3.1.0
    - importlib_metadata  # [py<38]

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - importlib_resources

about:
  home: https://github.com/python/importlib_resources
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Backport of Python 3.7's standard library `importlib.resources`
  doc_url: https://importlib-resources.readthedocs.io
  dev_url: https://github.com/python/importlib_resources

extra:
  recipe-maintainers:
    - ocefpaf
