{% set version = "5.1.4" %}

package:
  name: importlib_resources
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/importlib_resources/importlib_resources-{{ version }}.tar.gz
  sha256: 54161657e8ffc76596c4ede7080ca68cb02962a2e074a2586b695a93a925d36e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools_scm >=3.4.1
    # setuptools_scm[toml]
    - toml
  run:
    - python
    - pathlib2  # [py27]
    - typing  # [py<35]
    - zipp >=0.4  # [py<38]
    - singledispatch  # [py<34]
    - importlib_metadata  # [py<38]

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - importlib_resources

about:
  home: http://importlib-resources.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE
  summary: Backport of Python 3.7's standard library `importlib.resources`

extra:
  recipe-maintainers:
    - ocefpaf
