{% set version = "5.1.4" %}

package:
  name: importlib_resources
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/importlib_resources/importlib_resources-{{ version }}.tar.gz
  sha256: 54161657e8ffc76596c4ede7080ca68cb02962a2e074a2586b695a93a925d36e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - wheel
    - setuptools
  run:
    - python >=3.6
    - zipp >=3.1.0
    - importlib_metadata  # [py<38]

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - importlib_resources

about:
  home: https://github.com/python/importlib_resources
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Backport of Python 3.7's standard library `importlib.resources`
  doc_url: https://importlib-resources.readthedocs.io
  dev_url: https://github.com/python/importlib_resources

extra:
  recipe-maintainers:
    - ocefpaf
