{% set version = "5.4.0" %}

package:
  name: importlib_resources
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/importlib_resources/importlib_resources-{{ version }}.tar.gz
  sha256: d756e2f85dd4de2ba89be0b21dba2a3bbec2e871a42a3a16719258a11f87506b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm >=3.4.1
    # setuptools_scm[toml]
    - toml
  run:
    - python >=3.6
    - zipp >=3.1.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - importlib_resources

about:
  home: http://importlib-resources.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE
  summary: Backport of Python 3.7's standard library `importlib.resources`

extra:
  recipe-maintainers:
    - ocefpaf
