travis:
  secure:
    BINSTAR_TOKEN: prX6V8lX3GRJFKSkEePWxjkQpwFXVnPRxVNUrtjgldqq8IMrCxF6p0vU0DjELGBqmFt/z/LqvHvPYAKsylSfxYxh1dhgicFZXDJDnMMeujLDnMQCyIZdfIKXZSzDLB9w/5HV746d1s1c4taPHZRUq4w4+UXpyHssrFdZVbZSa10e3ppWBzIQWkCwKdGrb6plYdgx8mv4xOcAxrMsMtvUad/BD3OkDj6eDnpZdepVrkpsTfq5yD+ayE94B717Tkb6GdNM5cw6Ozxftb5fz0FMZBoUbtLUxuQn3osYR9PYuv0RGTUm5U2OGZdpnMFPK23iNj0xCAbkn9BuWkjk5XO0cjZpL59ShWycgl9f5kvf/bzo4HW+fyQ9RzMT97NpGqhHTxDkyhUa7lf6S+Kh3BssCeCbjk6L1c4TKsuaSmFUs8DHft3UaK1u2BZ1ObS60Y8XRJ9xJlJtQp6Swbh060UkaLy9m1Afe++zREZ4AaLxsvvtOAvSGNBDhhDTmMi0UoZB87SS1wNL8eZpyRq3xAylDnWpzqdFHcFuZxsI2a6Ql2C1XmzC2HMDq9C3QqK8ei1PfmUQISNZ1udnbZAlo18bRwPzg1GCEAzwlcH93evraySC4xX57r1j7Uno/vZQJV1LSB2OsokqQvzYtvYXIvApuCNTx4IIBIT0DKtgeVqE1+I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
